### ISSUE TITLE
1.2 ROADMAP

### ISSUE THREAD

**Issue by mcasimir** [mcasimir/mobile-angular-ui#109]
1.2 development goes on: https://github.com/mcasimir/mobile-angular-ui/tree/1.2
# Goals
- Do everything the angular way
- Take care of deprecated stuffs
- Change bootstrap style as less as possible to let user customize same variables as bootstrap
- Provide tools to create a true mobile-like interaction through gestures
- Keep controllers as free as possible from UI logic:
  - Avoid pollute controllers with simple UI stuffs like show/hide
  - Automatic garbage collect and clean up of directives on scope disposal
  - Use $broadcast in place of $emit (happens to be fast enough now).
- Cleaner and faster build process:
  - Use gulp and plugins in place of grunt
  - Extract part of build process to external libs
- Use JSHint to deliver safer Js code
# Tasks

[ ] Test Transform support for any browser
[ ] Test yieldTo should work despite is added before or after contentFor
[ ] Test ui-switch directive
[ ] Ui switch should work with swipe if present
[ ] Transform should support 3d transforms too 
[ ] Generalize exporting SharedState states to query params
[ ] `swipe` module should provide directives too
[ ] ui-\* should not take into account `$scope` for efficiency but should work with `ng-repeat` if possible
[ ] Support for drag gestures, eg. to create snap.js like sidebars and swipeable/draggable carousels, drag to refresh... (Needs a robust way to retrieve coordinates mixing translate3d and static/relative positioning) should be something as capable as http://pep.briangonzalez.org/.
[ ] Move `.scrollable` to core? (needs moving css style to js)
- [x] Scrollable events (i.e. foundation for drag to refresh, load more on scroll end...)
- [x] Better support for MS Devices
- [x] Drop Toggleable for SharedState
  - have a more concise syntax
  - support before/after-activate/inactivate events
  - control behavior on outer-clicks
  - bind toggleable state to ngModel
  - support ngChange
  - react to history back
- [x] Re-add modals
- [x] Overlays becomes a styling for modals: Adding `.overlay` class to a modal makes it an overlay
- [x] Less invasive and less verbose form/panel helpers
- [x] Add `.scrollable-header`/`.scrollable-footer`
- [x] Support for ng-if/ng-show/ng-hide with navbars and scrollables
# Generator
- [x] Document in core Getting Started
- [ ] Add JSHint
- [ ] Use lodash templates to implement Environments
# Collaborate
- Suggest your own!
