### ISSUE TITLE
Discuss ROADMAP for Mobile Angular UI 1.1

### ISSUE THREAD

**Issue by mcasimir** [mcasimir/mobile-angular-ui#4]
This is an ongoing document to identify features and improvements for the first final release.

**Feel free to provide feedback and suggestions here!**
## ROADMAP
- [x] Distribute a js not including angular.js and common angular.js modules like ngRoute, along with a standalone version.
- [x] Switch from ngTouch to fastclick
- [x] Use css 3d transforms to improve responsiveness and speed
- [x] Touch enabled carousel (#11)
- [x] Native looking switch control
- [x] Fix major issues involving scroll and overlays 
- [x] Make it Phonegap/Cordova ready (it should be now, just need to be tested)
- [x] Rename bs-input to something more understandable (eg. `form-control`)
- [x] Feature Freeze
- [x] Use less variables in place of hard-coded colors and sizes
- [x] Profile to find possible memory leaks in callbacks
- [x] Better form styling with horizontal layout support (to be released soon)
- [x] Make switch compatible with ng-click/ng-change
- [x] Include responsive grid .sm in base.css
- [x] Include responsive grid  .md .lg in desktop.css
- [x] Twitter account/Blog with changes
- [x] Update FontAwesome #74
- [ ] Support `select` with `.form-control`.
- [ ] Support `form-control-feedback`.
- [ ] Support scrollable in tabs
- [x] Create a grunt task to put :hover apart and re-add in desktop (Fix #75)
- [ ] Create a few toy apps / Collect existing apps made by users to prove its potential
- [ ] F.A.Q. 

Bugs: 
- [ ] Use 2D translateX with switch to solve #73
- [ ] Add by default -webkit-transform: translate3d(0,0,0) to .scrollable-content \* to fix ios5
- [ ] Fix #77 
- [ ] Fix #82
- [ ] Fix: https://muut.com/mobileangularui#!/mobileangularui/js:bug-in-demo-when-device-ori
- [ ] Decide wether to fix #14 or add an entry to the faq with possible fixes.

Wont:
- ~~Add gestures support with hammer.js~~
- ~~Profiling Demo by device~~
- ~~Separate bootstrap related css from mobile-angular-ui.css to allow use a different build of bootstrap, or another css framework at all.. maybe it would mean to drop bs-panel, bs-input~~ (mobile angular ui relies too much on bootstrap to do so)

Demanded to 1.2
- Support for drag gestures, eg. to create snap.js like sidebars and swipeable/draggable carousels, drag to refresh... (Needs a robust way to retrieve coordinates mixing translate3d and static/relative positioning) should be something as capable as http://pep.briangonzalez.org/.
- Scrollable events (i.e. foundation for drag to refresh, load more on scroll end...)
- Better support for MS Devices
- Toggle/Toggleable directive improvements:
  - fire element along with events
  - have a more concise syntax
  - support before/after-activate/inactivate events
  - control behavior on outer-clicks
  - bind toggleable state to ngModel
  - support ngChange
  - react to history back

Suggest your own!

**Comment by robertobock** [comment]
Where is the tutorial? I am gonna take the example as a guide for me.
